version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: /WebApi/Dockerfile
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5000:5000"
      - "5001:5001"
    restart: on-failure