name: .NET
version: 2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

workflows:
  build_and_test:
    jobs:
      - build:
          context: 
            - context
      - test:
          context:
            - context
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - build-tools/install-ci-tools
      - run:
          name: Restore dependencies
          command: dotnet restore
          working_directory: Backend
      - run:
          name: Build
          working_directory: Backend
          command: |
            apt update
            apt install sudo -y
            dotnet build -p:RunAnalyzersDuringBuild=true
      - run:
          name: SonarQube
          working_directory: Backend
          command: |
            sudo apt install default-jdk
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet tool install --global dotnet-sonarscanner
            dotnet-sonarscanner begin /k:"ProiectDotNet" /d:sonar.host.url="http://localhost:9000"  /d:sonar.login="d1c3b6d57203a339957c0dbeaac683f836760a5e"
            dotnet build
            dotnet-sonarscanner end /d:sonar.login="d1c3b6d57203a339957c0dbeaac683f836760a5e"
  test:
    working_directory: Backend
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Test
          working_directory: Backend
          command: |
            dotnet test --logger:"xunit;LogFilePath=test_result.xml"
orbs:
    build-tools: circleci/build-tools@3.0.0
