name: .NET
version: 2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

workflows:
  build_and_test:
    jobs:
      - build:
          context: 
            - context
            - SonarCloud
      - test:
          context:
            - context
            - SonarCloud
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - build-tools/install-ci-tools
      - run:
          name: Restore dependencies
          command: dotnet restore
          working_directory: Backend
      - run:
          name: Build
          working_directory: Backend
          command: |
            apt update
            apt install sudo -y
            wget -qO -y https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | sudo apt-key add -
            sudo apt -y install software-properties-common
            sudo add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
            sudo apt -y install  adoptopenjdk-13-hotspot
            dotnet build -p:RunAnalyzersDuringBuild=true
      #- sonarcloud/scan-docker
      # - sonarcloud-dotnet/setup-sonar
      # - sonarcloud-dotnet/run-scan:
      #     sonarlogin: 
      #     organization: dotnetproiect
      #     project_key: curcaandrei_ProiectDotNet
      # - sonarcloud-dotnet/end-scan:
      #     sonarlogin: deabe192f96e1d51f66463f6d475eef172b48cdf
      - sonarcloud-dotnet/setup-sonar
      - sonarcloud-dotnet/run-scan:
          project_key: curcaandrei_ProiectDotNet 
          sonarlogin: deabe192f96e1d51f66463f6d475eef172b48cdf 
          organization: dotnetproiect 
          build_path: Backend 
          test_path: Backend 
  test:
    working_directory: Backend
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          working_directory: artifacts
          command: |
            echo "my artifact file" > art-1;
            mkdir -p artifacts/artifacts;
            echo "my artifact files in a dir" > art-2;
      - store_artifacts:
          path: artifacts/art-1
          destination: artifact-file
      - store_artifacts:
          path: artifacts/artifacts
  
      - run:
          name: Test
          working_directory: Backend
          command: |
            dotnet test --logger:"xunit;LogFilePath=test_result.xml"
orbs:
    #sonarcloud: sonarsource/sonarcloud@1.0.1
    sonarcloud-dotnet: bestsellerit/sonarcloud-dotnet@0.0.1
    build-tools: circleci/build-tools@3.0.0
