name: .NET
version: 2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

workflows:
  build_and_test:
    jobs:
      - build:
          context: context
      - test:
          context: context

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore
          working_directory: Backend
      - run:
          name: Build
          working_directory: Backend
          command: |
            dotnet build --no-restore

  test:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Test
          working_directory: Backend
          command: |
            dotnet test