name: .NET
version: 2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

workflows:
  build_and_test:
    jobs:
      - build:
          context: 
            - context
            - SonarCloud
      - test:
          context:
            - context
            - SonarCloud
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - build-tools/install-ci-tools
      - run:
          name: Restore dependencies
          command: dotnet restore
          working_directory: Backend
      - run:
          name: Build
          working_directory: Backend
          command: |
            apt update
            apt install sudo -y
            dotnet build -p:RunAnalyzersDuringBuild=true
      - sonarcloud/scan
      # - sonarcloud-dotnet/setup-sonar
      # - sonarcloud-dotnet/run-scan:
      #     sonarlogin: 
      #     organization: dotnetproiect
      #     project_key: curcaandrei_ProiectDotNet
      # - sonarcloud-dotnet/end-scan:
      #     sonarlogin: deabe192f96e1d51f66463f6d475eef172b48cdf
  test:
    working_directory: Backend
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          working_directory: artifacts
          command: |
            echo "my artifact file" > art-1;
            mkdir -p artifacts/artifacts;
            echo "my artifact files in a dir" > art-2;
      - store_artifacts:
          path: artifacts/art-1
          destination: artifact-file
      - store_artifacts:
          path: artifacts/artifacts
  
      - run:
          name: Test
          working_directory: Backend
          command: |
            dotnet test --logger:"xunit;LogFilePath=test_result.xml"
orbs:
    sonarcloud: sonarsource/sonarcloud@1.0.1
    build-tools: circleci/build-tools@3.0.0
