name: .NET
version: 2.1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/dotnet:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: echo "this is the build job"
  test:
    docker:
      - image: cimg/dotnet:latest
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - run: echo "this is the test job"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
      - test
