
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: Backend
      - name: Build
        run: dotnet build --no-restore
        working-directory: Backend
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: Backend
      - name: GenerateReport
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        working-directory: Backend
      - name: GetXML
        run: dotnet test --collect:"XPlat Code Coverage"
        working-directory: Backend
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          dotnet-version: 6.0.x
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
         dotnet-version: 6.0.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
