
name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Backend
    - name: Setup latest .NET SDKs
      uses: Elskom/setup-latest-dotnet@v1
    - name: Build
      run: dotnet build --no-restore
      working-directory: Backend
#     - name: Test
#       run: dotnet test --no-build --verbosity normal
    - name: Test Reporter
      uses: dorny/test-reporter@v1.5.0
